import type { StatsSummary, GenrePlaytime, RecentSession, Game } from '@/types/models'
import { parseStoredUtcDate } from '@/features/library/utils/format'

export type MilestoneCategory =
  'playtime' | 'collection' | 'streaks' | 'sessions' | 'habits' | 'genres' | 'devotion' | 'mastery'

export interface Milestone {
  id: string
  category: MilestoneCategory
  title: string
  subtitle: string
  description: string
  tier: 'bronze' | 'silver' | 'gold' | 'platinum'
  iconName: string
  unlocked: boolean
  progressPercent: number
  progressLabel: string
}

export function evaluateMilestones({
  summary,
  genres,
  sessions,
  streak,
  games,
}: {
  summary: StatsSummary | undefined
  genres: GenrePlaytime[] | undefined
  sessions: RecentSession[] | undefined
  streak: number
  games?: Game[]
}): Milestone[] {
  // Aggregate Basic Playtime Stats
  const totalSeconds = summary?.total_playtime_seconds ?? 0
  const totalHours = Math.floor(totalSeconds / 3600)
  const totalMinutes = Math.floor(totalSeconds / 60)
  const totalGames = summary?.total_games ?? games?.length ?? 0
  const installedGames =
    summary?.installed_games ?? games?.filter((g) => g.executable_path !== null).length ?? 0
  const topGameHours = summary?.most_played_game
    ? Math.floor(summary.most_played_game.total_playtime_seconds / 3600)
    : 0
  const topGameSeconds = summary?.most_played_game?.total_playtime_seconds ?? 0

  // Session Stats
  const validSessions = sessions ?? []
  const sessionCount = validSessions.length
  const hasSessions = sessionCount > 0 || totalHours > 0
  const longestSessionHours = Math.max(
    ...validSessions.map((s) => (s.duration_seconds ? s.duration_seconds / 3600 : 0)),
    0,
  )
  const longestSessionMinutes = Math.max(
    ...validSessions.map((s) => (s.duration_seconds ? s.duration_seconds / 60 : 0)),
    0,
  )

  // Genre Stats
  const validGenres = genres ?? []
  const activeGenres = validGenres.filter((g) => g.total_playtime_seconds > 0)
  const genreCount = activeGenres.length
  const genreHours = (pattern: string) => {
    const matched = validGenres.filter((g) => g.genre.toLowerCase().includes(pattern.toLowerCase()))
    const secs = matched.reduce((acc, g) => acc + g.total_playtime_seconds, 0)
    return Math.floor(secs / 3600)
  }

  // Circadian Rhythms
  let nightSessions = 0
  let witchingHourSessions = 0
  let dawnSessions = 0
  let morningSessions = 0
  let lunchSessions = 0
  let afternoonSessions = 0
  let eveningSessions = 0
  let fridayNightSessions = 0
  let weekendSessions = 0
  let sundaySessions = 0
  let mondaySessions = 0
  let wednesdaySessions = 0

  for (const s of validSessions) {
    const d = parseStoredUtcDate(s.started_at)
    if (!d) continue
    const h = d.getHours()
    const day = d.getDay() // 0 = Sunday, 1 = Monday, 5 = Friday, 6 = Saturday

    if (h >= 0 && h < 5) nightSessions++
    if (h >= 3 && h < 4) witchingHourSessions++
    if (h >= 5 && h < 8) dawnSessions++
    if (h >= 8 && h < 12) morningSessions++
    if (h >= 12 && h < 14) lunchSessions++
    if (h >= 14 && h < 17) afternoonSessions++
    if (h >= 17 && h < 22) eveningSessions++

    if (day === 5 && h >= 18) fridayNightSessions++
    if (day === 0 || day === 6) weekendSessions++
    if (day === 0) sundaySessions++
    if (day === 1) mondaySessions++
    if (day === 3) wednesdaySessions++
  }

  // Games & Library Curation Stats
  const validGames = games ?? []
  const playedGamesCount = validGames.filter((g) => g.total_playtime_seconds > 0).length
  const totalDiskBytes = validGames.reduce((acc, g) => acc + (g.install_size_bytes ?? 0), 0)
  const totalDiskGB = Math.round(totalDiskBytes / (1024 * 1024 * 1024))
  const taggedGamesCount = validGames.filter((g) => (g.tag_ids?.length ?? 0) > 0).length
  const customCoverCount = validGames.filter((g) => Boolean(g.cover_path)).length

  // Helper for progress calculation
  const p = (current: number, target: number) => Math.min(100, Math.round((current / target) * 100))

  const milestones: Milestone[] = [
    // ══════════════════════════════════════════════════════════════════════════
    // 1. PLAYTIME & DEDICATION (15 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'time_1h',
      category: 'playtime',
      title: 'First Hour',
      subtitle: 'The Journey Begins',
      description: 'Log your very first hour of gameplay in Nexus Launcher.',
      tier: 'bronze',
      iconName: 'Clock',
      unlocked: totalHours >= 1 || totalMinutes >= 60,
      progressPercent: p(totalMinutes, 60),
      progressLabel: `${Math.min(totalMinutes, 60)} / 60 Mins`,
    },
    {
      id: 'time_5h',
      category: 'playtime',
      title: 'Warming Up',
      subtitle: 'Getting the Hang of It',
      description: 'Accumulate 5 hours of total lifetime playtime.',
      tier: 'bronze',
      iconName: 'Clock',
      unlocked: totalHours >= 5,
      progressPercent: p(totalHours, 5),
      progressLabel: `${Math.min(totalHours, 5)} / 5 Hours`,
    },
    {
      id: 'time_10h',
      category: 'playtime',
      title: 'Double Digits',
      subtitle: 'Solid Foundation',
      description: 'Reach 10 hours of verified gaming time across your library.',
      tier: 'bronze',
      iconName: 'Zap',
      unlocked: totalHours >= 10,
      progressPercent: p(totalHours, 10),
      progressLabel: `${Math.min(totalHours, 10)} / 10 Hours`,
    },
    {
      id: 'time_25h',
      category: 'playtime',
      title: 'Seasoned Explorer',
      subtitle: 'Quarter-Century Mark',
      description: 'Log 25 hours exploring different virtual worlds.',
      tier: 'silver',
      iconName: 'Zap',
      unlocked: totalHours >= 25,
      progressPercent: p(totalHours, 25),
      progressLabel: `${Math.min(totalHours, 25)} / 25 Hours`,
    },
    {
      id: 'time_50h',
      category: 'playtime',
      title: 'Half-Century Veteran',
      subtitle: 'True Devotion',
      description: 'Accumulate 50 hours of total gameplay in Nexus.',
      tier: 'silver',
      iconName: 'Flame',
      unlocked: totalHours >= 50,
      progressPercent: p(totalHours, 50),
      progressLabel: `${Math.min(totalHours, 50)} / 50 Hours`,
    },
    {
      id: 'time_75h',
      category: 'playtime',
      title: 'Battle-Hardened',
      subtitle: 'Relentless Drive',
      description: 'Log 75 hours of action, adventure, and digital triumph.',
      tier: 'silver',
      iconName: 'Shield',
      unlocked: totalHours >= 75,
      progressPercent: p(totalHours, 75),
      progressLabel: `${Math.min(totalHours, 75)} / 75 Hours`,
    },
    {
      id: 'time_100h',
      category: 'playtime',
      title: 'Century Legend',
      subtitle: '100-Hour Odyssey',
      description: 'Achieve 100 hours of total lifetime logged playtime.',
      tier: 'gold',
      iconName: 'Crown',
      unlocked: totalHours >= 100,
      progressPercent: p(totalHours, 100),
      progressLabel: `${Math.min(totalHours, 100)} / 100 Hours`,
    },
    {
      id: 'time_150h',
      category: 'playtime',
      title: 'Realm Voyager',
      subtitle: 'Beyond Horizons',
      description: 'Surpass 150 hours of total active playtime.',
      tier: 'gold',
      iconName: 'Compass',
      unlocked: totalHours >= 150,
      progressPercent: p(totalHours, 150),
      progressLabel: `${Math.min(totalHours, 150)} / 150 Hours`,
    },
    {
      id: 'time_200h',
      category: 'playtime',
      title: 'Digital Vanguard',
      subtitle: 'Two Centuries of Gaming',
      description: 'Log 200 hours of gaming within the Nexus ecosystem.',
      tier: 'gold',
      iconName: 'Target',
      unlocked: totalHours >= 200,
      progressPercent: p(totalHours, 200),
      progressLabel: `${Math.min(totalHours, 200)} / 200 Hours`,
    },
    {
      id: 'time_300h',
      category: 'playtime',
      title: 'Chrono Weaver',
      subtitle: 'Time Lord of Games',
      description: 'Accumulate 300 hours of verifiable gameplay.',
      tier: 'gold',
      iconName: 'Sparkles',
      unlocked: totalHours >= 300,
      progressPercent: p(totalHours, 300),
      progressLabel: `${Math.min(totalHours, 300)} / 300 Hours`,
    },
    {
      id: 'time_400h',
      category: 'playtime',
      title: 'Grand Overlord',
      subtitle: 'Supreme Commitment',
      description: 'Achieve 400 hours of verified in-game telemetry.',
      tier: 'gold',
      iconName: 'Trophy',
      unlocked: totalHours >= 400,
      progressPercent: p(totalHours, 400),
      progressLabel: `${Math.min(totalHours, 400)} / 400 Hours`,
    },
    {
      id: 'time_500h',
      category: 'playtime',
      title: 'Ascended Titan',
      subtitle: 'Half-Millennium Feat',
      description: 'Surpass 500 hours of total lifetime playtime.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: totalHours >= 500,
      progressPercent: p(totalHours, 500),
      progressLabel: `${Math.min(totalHours, 500)} / 500 Hours`,
    },
    {
      id: 'time_750h',
      category: 'playtime',
      title: 'Immortal Sovereign',
      subtitle: 'Legend of the Matrix',
      description: 'Reach an astounding 750 hours of total playtime.',
      tier: 'platinum',
      iconName: 'Flame',
      unlocked: totalHours >= 750,
      progressPercent: p(totalHours, 750),
      progressLabel: `${Math.min(totalHours, 750)} / 750 Hours`,
    },
    {
      id: 'time_1000h',
      category: 'playtime',
      title: 'Millennium Grandmaster',
      subtitle: '1,000 Hours of Glory',
      description: 'Cross the monumental milestone of 1,000 total hours played.',
      tier: 'platinum',
      iconName: 'Sparkles',
      unlocked: totalHours >= 1000,
      progressPercent: p(totalHours, 1000),
      progressLabel: `${Math.min(totalHours, 1000)} / 1,000 Hours`,
    },
    {
      id: 'time_2000h',
      category: 'playtime',
      title: 'Omnipresent Entity',
      subtitle: 'Living Legend',
      description: 'Reach 2,000 hours of lifetime gameplay.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: totalHours >= 2000,
      progressPercent: p(totalHours, 2000),
      progressLabel: `${Math.min(totalHours, 2000)} / 2,000 Hours`,
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 2. LIBRARY & COLLECTION (15 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'lib_1',
      category: 'collection',
      title: 'First Acquisition',
      subtitle: 'Library Inception',
      description: 'Add your first title into your Nexus game library.',
      tier: 'bronze',
      iconName: 'Gamepad2',
      unlocked: totalGames >= 1,
      progressPercent: p(totalGames, 1),
      progressLabel: `${Math.min(totalGames, 1)} / 1 Game`,
    },
    {
      id: 'lib_3',
      category: 'collection',
      title: 'Triple Threat',
      subtitle: 'A Promising Trio',
      description: 'Assemble at least 3 games in your library.',
      tier: 'bronze',
      iconName: 'Layers',
      unlocked: totalGames >= 3,
      progressPercent: p(totalGames, 3),
      progressLabel: `${Math.min(totalGames, 3)} / 3 Games`,
    },
    {
      id: 'lib_5',
      category: 'collection',
      title: 'Squad Roster',
      subtitle: 'Five Strong',
      description: 'Grow your personal gaming library to 5 titles.',
      tier: 'bronze',
      iconName: 'Gamepad2',
      unlocked: totalGames >= 5,
      progressPercent: p(totalGames, 5),
      progressLabel: `${Math.min(totalGames, 5)} / 5 Games`,
    },
    {
      id: 'lib_10',
      category: 'collection',
      title: 'Master Collector',
      subtitle: 'Vault Architect',
      description: 'Assemble a library containing 10 or more titles.',
      tier: 'bronze',
      iconName: 'Library',
      unlocked: totalGames >= 10,
      progressPercent: p(totalGames, 10),
      progressLabel: `${Math.min(totalGames, 10)} / 10 Games`,
    },
    {
      id: 'lib_15',
      category: 'collection',
      title: 'Curator in Training',
      subtitle: 'Expanding Horizons',
      description: 'Collect 15 unique games in your command vault.',
      tier: 'silver',
      iconName: 'Library',
      unlocked: totalGames >= 15,
      progressPercent: p(totalGames, 15),
      progressLabel: `${Math.min(totalGames, 15)} / 15 Games`,
    },
    {
      id: 'lib_25',
      category: 'collection',
      title: 'Chief Archivist',
      subtitle: 'Quarter-Hundred Vault',
      description: 'Amass 25 titles in your Nexus launcher collection.',
      tier: 'silver',
      iconName: 'FolderArchive',
      unlocked: totalGames >= 25,
      progressPercent: p(totalGames, 25),
      progressLabel: `${Math.min(totalGames, 25)} / 25 Games`,
    },
    {
      id: 'lib_40',
      category: 'collection',
      title: 'Vault Overseer',
      subtitle: 'Expansive Horizons',
      description: 'Build your collection to 40 games.',
      tier: 'gold',
      iconName: 'Library',
      unlocked: totalGames >= 40,
      progressPercent: p(totalGames, 40),
      progressLabel: `${Math.min(totalGames, 40)} / 40 Games`,
    },
    {
      id: 'lib_50',
      category: 'collection',
      title: 'Hoarder of Worlds',
      subtitle: '50-Title Fortress',
      description: 'Expand your gaming archive to 50 titles.',
      tier: 'gold',
      iconName: 'Trophy',
      unlocked: totalGames >= 50,
      progressPercent: p(totalGames, 50),
      progressLabel: `${Math.min(totalGames, 50)} / 50 Games`,
    },
    {
      id: 'lib_75',
      category: 'collection',
      title: 'The Great Curator',
      subtitle: 'Colossal Vault',
      description: 'Assemble an impressive collection of 75 games.',
      tier: 'gold',
      iconName: 'Layers',
      unlocked: totalGames >= 75,
      progressPercent: p(totalGames, 75),
      progressLabel: `${Math.min(totalGames, 75)} / 75 Games`,
    },
    {
      id: 'lib_100',
      category: 'collection',
      title: 'The Grand Citadel',
      subtitle: '100-Game Dynasty',
      description: 'Achieve a legendary library containing 100 titles.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: totalGames >= 100,
      progressPercent: p(totalGames, 100),
      progressLabel: `${Math.min(totalGames, 100)} / 100 Games`,
    },
    {
      id: 'install_1',
      category: 'collection',
      title: 'Ready for Battle',
      subtitle: 'First Deployment',
      description: 'Have at least 1 verified installed game ready to launch.',
      tier: 'bronze',
      iconName: 'HardDrive',
      unlocked: installedGames >= 1,
      progressPercent: p(installedGames, 1),
      progressLabel: `${Math.min(installedGames, 1)} / 1 Installed`,
    },
    {
      id: 'install_5',
      category: 'collection',
      title: 'Armed to the Teeth',
      subtitle: 'Five Ready to Run',
      description: 'Keep 5 or more games installed and combat ready simultaneously.',
      tier: 'silver',
      iconName: 'HardDrive',
      unlocked: installedGames >= 5,
      progressPercent: p(installedGames, 5),
      progressLabel: `${Math.min(installedGames, 5)} / 5 Installed`,
    },
    {
      id: 'install_10',
      category: 'collection',
      title: 'Storage Titan',
      subtitle: 'Digital Warehouse',
      description: 'Maintain 10 installed games ready on your local storage.',
      tier: 'gold',
      iconName: 'HardDrive',
      unlocked: installedGames >= 10,
      progressPercent: p(installedGames, 10),
      progressLabel: `${Math.min(installedGames, 10)} / 10 Installed`,
    },
    {
      id: 'disk_50gb',
      category: 'collection',
      title: 'Heavy Duty Storage',
      subtitle: '50 GB Deployed',
      description: 'Have over 50 GB of gaming installations managed by Nexus.',
      tier: 'silver',
      iconName: 'Disc',
      unlocked: totalDiskGB >= 50,
      progressPercent: p(totalDiskGB, 50),
      progressLabel: `${Math.min(totalDiskGB, 50)} / 50 GB`,
    },
    {
      id: 'disk_250gb',
      category: 'collection',
      title: 'Quarter-Terabyte Armada',
      subtitle: 'Massive Footprint',
      description: 'Manage 250 GB or more of game installations.',
      tier: 'gold',
      iconName: 'Disc',
      unlocked: totalDiskGB >= 250,
      progressPercent: p(totalDiskGB, 250),
      progressLabel: `${Math.min(totalDiskGB, 250)} / 250 GB`,
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 3. STREAKS & CONSISTENCY (12 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'streak_2',
      category: 'streaks',
      title: 'Back-to-Back',
      subtitle: 'Consecutive Days',
      description: 'Game on 2 consecutive days without breaking your rhythm.',
      tier: 'bronze',
      iconName: 'Flame',
      unlocked: streak >= 2,
      progressPercent: p(streak, 2),
      progressLabel: `${Math.min(streak, 2)} / 2 Days`,
    },
    {
      id: 'streak_3',
      category: 'streaks',
      title: 'Hat Trick',
      subtitle: 'Three in a Row',
      description: 'Maintain a 3-day unbroken gaming streak.',
      tier: 'bronze',
      iconName: 'Flame',
      unlocked: streak >= 3,
      progressPercent: p(streak, 3),
      progressLabel: `${Math.min(streak, 3)} / 3 Days`,
    },
    {
      id: 'streak_5',
      category: 'streaks',
      title: 'Workweek Champion',
      subtitle: 'Five Days Strong',
      description: 'Log into Nexus 5 days in a row.',
      tier: 'bronze',
      iconName: 'Zap',
      unlocked: streak >= 5,
      progressPercent: p(streak, 5),
      progressLabel: `${Math.min(streak, 5)} / 5 Days`,
    },
    {
      id: 'streak_7',
      category: 'streaks',
      title: 'Unstoppable Momentum',
      subtitle: '7-Day Hot Streak',
      description: 'Maintain an unbroken daily gaming streak for 7 consecutive days.',
      tier: 'silver',
      iconName: 'Flame',
      unlocked: streak >= 7,
      progressPercent: p(streak, 7),
      progressLabel: `${Math.min(streak, 7)} / 7 Days`,
    },
    {
      id: 'streak_10',
      category: 'streaks',
      title: 'Tenacious Ten',
      subtitle: 'Double-Digit Streak',
      description: 'Reach a continuous 10-day streak.',
      tier: 'silver',
      iconName: 'Flame',
      unlocked: streak >= 10,
      progressPercent: p(streak, 10),
      progressLabel: `${Math.min(streak, 10)} / 10 Days`,
    },
    {
      id: 'streak_14',
      category: 'streaks',
      title: 'Fortnight of Glory',
      subtitle: 'Two Full Weeks',
      description: 'Keep your streak burning for 14 continuous days.',
      tier: 'silver',
      iconName: 'Shield',
      unlocked: streak >= 14,
      progressPercent: p(streak, 14),
      progressLabel: `${Math.min(streak, 14)} / 14 Days`,
    },
    {
      id: 'streak_21',
      category: 'streaks',
      title: 'Habit of Excellence',
      subtitle: '21-Day Ritual',
      description: 'Psychologists say 21 days forms a habit — you just did.',
      tier: 'gold',
      iconName: 'Target',
      unlocked: streak >= 21,
      progressPercent: p(streak, 21),
      progressLabel: `${Math.min(streak, 21)} / 21 Days`,
    },
    {
      id: 'streak_30',
      category: 'streaks',
      title: 'Monthly Phenomenon',
      subtitle: 'Full Month Unbroken',
      description: 'Log verified gaming sessions across 30 consecutive days.',
      tier: 'gold',
      iconName: 'Crown',
      unlocked: streak >= 30,
      progressPercent: p(streak, 30),
      progressLabel: `${Math.min(streak, 30)} / 30 Days`,
    },
    {
      id: 'streak_60',
      category: 'streaks',
      title: 'Iron Discipline',
      subtitle: '60 Consecutive Days',
      description: 'Two months of unwavering gaming determination.',
      tier: 'gold',
      iconName: 'Trophy',
      unlocked: streak >= 60,
      progressPercent: p(streak, 60),
      progressLabel: `${Math.min(streak, 60)} / 60 Days`,
    },
    {
      id: 'streak_90',
      category: 'streaks',
      title: 'Quarterly Conqueror',
      subtitle: '90-Day Mastery',
      description: 'Maintain your gaming streak across an entire quarter.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: streak >= 90,
      progressPercent: p(streak, 90),
      progressLabel: `${Math.min(streak, 90)} / 90 Days`,
    },
    {
      id: 'streak_180',
      category: 'streaks',
      title: 'Half-Year Legend',
      subtitle: '180-Day Dedication',
      description: 'Six full months without missing a single day of gaming.',
      tier: 'platinum',
      iconName: 'Flame',
      unlocked: streak >= 180,
      progressPercent: p(streak, 180),
      progressLabel: `${Math.min(streak, 180)} / 180 Days`,
    },
    {
      id: 'streak_365',
      category: 'streaks',
      title: 'Nexus Solar Deity',
      subtitle: 'A Full 365 Days',
      description: 'An entire uninterrupted year of daily gaming sessions.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: streak >= 365,
      progressPercent: p(streak, 365),
      progressLabel: `${Math.min(streak, 365)} / 365 Days`,
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 4. SESSION INTENSITY & MARATHONS (12 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'sess_first',
      category: 'sessions',
      title: 'First Blood',
      subtitle: 'Session Inception',
      description: 'Log your first verified gameplay session in Nexus Launcher.',
      tier: 'bronze',
      iconName: 'Sparkles',
      unlocked: hasSessions,
      progressPercent: hasSessions ? 100 : 0,
      progressLabel: hasSessions ? 'Completed' : '0 / 1 Session',
    },
    {
      id: 'sess_10',
      category: 'sessions',
      title: 'Nexus Regular',
      subtitle: '10 Sessions Logged',
      description: 'Complete 10 distinct gameplay sessions.',
      tier: 'bronze',
      iconName: 'Play',
      unlocked: sessionCount >= 10,
      progressPercent: p(sessionCount, 10),
      progressLabel: `${Math.min(sessionCount, 10)} / 10 Sessions`,
    },
    {
      id: 'sess_25',
      category: 'sessions',
      title: 'Combat Veteran',
      subtitle: '25 Sorties Completed',
      description: 'Log 25 gaming sessions across your collection.',
      tier: 'silver',
      iconName: 'Activity',
      unlocked: sessionCount >= 25,
      progressPercent: p(sessionCount, 25),
      progressLabel: `${Math.min(sessionCount, 25)} / 25 Sessions`,
    },
    {
      id: 'sess_50',
      category: 'sessions',
      title: 'Console Commander',
      subtitle: '50 Engagements',
      description: 'Record 50 verified gameplay sessions.',
      tier: 'silver',
      iconName: 'Activity',
      unlocked: sessionCount >= 50,
      progressPercent: p(sessionCount, 50),
      progressLabel: `${Math.min(sessionCount, 50)} / 50 Sessions`,
    },
    {
      id: 'sess_100',
      category: 'sessions',
      title: 'Centennial Operator',
      subtitle: '100 Sessions in Orbit',
      description: 'Reach 100 recorded play sessions.',
      tier: 'gold',
      iconName: 'Trophy',
      unlocked: sessionCount >= 100,
      progressPercent: p(sessionCount, 100),
      progressLabel: `${Math.min(sessionCount, 100)} / 100 Sessions`,
    },
    {
      id: 'sess_250',
      category: 'sessions',
      title: 'Endless Expeditions',
      subtitle: '250 Missions Logged',
      description: 'Log 250 individual gameplay sessions.',
      tier: 'platinum',
      iconName: 'Sparkles',
      unlocked: sessionCount >= 250,
      progressPercent: p(sessionCount, 250),
      progressLabel: `${Math.min(sessionCount, 250)} / 250 Sessions`,
    },
    {
      id: 'mara_30m',
      category: 'sessions',
      title: 'Quick Skirmish',
      subtitle: '30-Minute Sprint',
      description: 'Complete a single gaming session lasting at least 30 minutes.',
      tier: 'bronze',
      iconName: 'Clock',
      unlocked: longestSessionMinutes >= 30,
      progressPercent: p(longestSessionMinutes, 30),
      progressLabel: `${Math.min(Math.round(longestSessionMinutes), 30)} / 30 Mins`,
    },
    {
      id: 'mara_1h',
      category: 'sessions',
      title: 'Full Match',
      subtitle: '60 Minutes Unbroken',
      description: 'Play continuously in one session for over 1 full hour.',
      tier: 'bronze',
      iconName: 'Clock',
      unlocked: longestSessionHours >= 1,
      progressPercent: p(longestSessionHours, 1),
      progressLabel: `${Math.min(Math.round(longestSessionHours * 10) / 10, 1)} / 1 Hour`,
    },
    {
      id: 'mara_2h',
      category: 'sessions',
      title: 'Deep Immersion',
      subtitle: '2-Hour Voyage',
      description: 'Engage in a continuous session exceeding 2 hours.',
      tier: 'silver',
      iconName: 'Zap',
      unlocked: longestSessionHours >= 2,
      progressPercent: p(longestSessionHours, 2),
      progressLabel: `${Math.min(Math.round(longestSessionHours * 10) / 10, 2)} / 2 Hours`,
    },
    {
      id: 'mara_3h',
      category: 'sessions',
      title: 'Marathon Runner',
      subtitle: 'Endurance Mastery',
      description: 'Complete an epic continuous gaming session lasting over 3 hours.',
      tier: 'silver',
      iconName: 'Zap',
      unlocked: longestSessionHours >= 3,
      progressPercent: p(longestSessionHours, 3),
      progressLabel: `${Math.min(Math.round(longestSessionHours * 10) / 10, 3)} / 3 Hours`,
    },
    {
      id: 'mara_5h',
      category: 'sessions',
      title: 'Endurance Titan',
      subtitle: '5-Hour Marathon',
      description: 'Sustain a continuous play session for over 5 uninterrupted hours.',
      tier: 'gold',
      iconName: 'Flame',
      unlocked: longestSessionHours >= 5,
      progressPercent: p(longestSessionHours, 5),
      progressLabel: `${Math.min(Math.round(longestSessionHours * 10) / 10, 5)} / 5 Hours`,
    },
    {
      id: 'mara_8h',
      category: 'sessions',
      title: 'The Great Odyssey',
      subtitle: '8-Hour Mega Marathon',
      description: 'Log a colossal session exceeding 8 hours of continuous play.',
      tier: 'platinum',
      iconName: 'Trophy',
      unlocked: longestSessionHours >= 8,
      progressPercent: p(longestSessionHours, 8),
      progressLabel: `${Math.min(Math.round(longestSessionHours * 10) / 10, 8)} / 8 Hours`,
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 5. CIRCADIAN & TIME-OF-DAY HABITS (14 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'habit_night',
      category: 'habits',
      title: 'Midnight Phantom',
      subtitle: 'Creature of the Night',
      description: 'Log a battle or quest between midnight and 5:00 AM.',
      tier: 'silver',
      iconName: 'Moon',
      unlocked: nightSessions >= 1,
      progressPercent: p(nightSessions, 1),
      progressLabel: nightSessions >= 1 ? 'Unlocked' : '0 / 1 Session',
    },
    {
      id: 'habit_night_5',
      category: 'habits',
      title: 'Nocturnal Overlord',
      subtitle: '5 Night Sorties',
      description: 'Log 5 distinct gameplay sessions between midnight and 5:00 AM.',
      tier: 'gold',
      iconName: 'Moon',
      unlocked: nightSessions >= 5,
      progressPercent: p(nightSessions, 5),
      progressLabel: `${Math.min(nightSessions, 5)} / 5 Night Sessions`,
    },
    {
      id: 'habit_witching',
      category: 'habits',
      title: 'Witching Hour',
      subtitle: '3:00 AM Phenomenon',
      description: 'Active session started during the haunting hour (3:00 AM - 4:00 AM).',
      tier: 'gold',
      iconName: 'Moon',
      unlocked: witchingHourSessions >= 1,
      progressPercent: witchingHourSessions >= 1 ? 100 : 0,
      progressLabel: witchingHourSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_dawn',
      category: 'habits',
      title: 'Dawn Patrol',
      subtitle: 'First Light',
      description: 'Log a morning quest between 5:00 AM and 8:00 AM.',
      tier: 'silver',
      iconName: 'Sun',
      unlocked: dawnSessions >= 1,
      progressPercent: dawnSessions >= 1 ? 100 : 0,
      progressLabel: dawnSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_morning',
      category: 'habits',
      title: 'Morning Glory',
      subtitle: 'Early Riser',
      description: 'Log a session during morning hours (8:00 AM - 12:00 PM).',
      tier: 'bronze',
      iconName: 'Sun',
      unlocked: morningSessions >= 1,
      progressPercent: morningSessions >= 1 ? 100 : 0,
      progressLabel: morningSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_lunch',
      category: 'habits',
      title: 'Lunch Break Operative',
      subtitle: 'Midday Mission',
      description: 'Sneak in a game session between 12:00 PM and 2:00 PM.',
      tier: 'bronze',
      iconName: 'Coffee',
      unlocked: lunchSessions >= 1,
      progressPercent: lunchSessions >= 1 ? 100 : 0,
      progressLabel: lunchSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_afternoon',
      category: 'habits',
      title: 'Afternoon Siesta',
      subtitle: 'Post-Noon Adventure',
      description: 'Log game sessions between 2:00 PM and 5:00 PM.',
      tier: 'bronze',
      iconName: 'Sun',
      unlocked: afternoonSessions >= 1,
      progressPercent: afternoonSessions >= 1 ? 100 : 0,
      progressLabel: afternoonSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_evening',
      category: 'habits',
      title: 'Prime Time Champion',
      subtitle: 'Golden Hour Gaming',
      description: 'Play during peak evening relaxation hours (5:00 PM - 10:00 PM).',
      tier: 'silver',
      iconName: 'Tv',
      unlocked: eveningSessions >= 1,
      progressPercent: eveningSessions >= 1 ? 100 : 0,
      progressLabel: eveningSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_friday',
      category: 'habits',
      title: 'Friday Night Fever',
      subtitle: 'Weekend Commences',
      description: 'Boot up a game on Friday evening after 6:00 PM.',
      tier: 'silver',
      iconName: 'Sparkles',
      unlocked: fridayNightSessions >= 1,
      progressPercent: fridayNightSessions >= 1 ? 100 : 0,
      progressLabel: fridayNightSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_weekend',
      category: 'habits',
      title: 'Weekend Warrior',
      subtitle: 'Saturday & Sunday Surge',
      description: 'Log sessions during the weekend.',
      tier: 'bronze',
      iconName: 'Gamepad2',
      unlocked: weekendSessions >= 1,
      progressPercent: weekendSessions >= 1 ? 100 : 0,
      progressLabel: weekendSessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_weekend_binge',
      category: 'habits',
      title: 'Sunday Slacker',
      subtitle: 'Endless Sunday',
      description: 'Play across multiple sessions on a Sunday.',
      tier: 'silver',
      iconName: 'Sofa',
      unlocked: sundaySessions >= 2,
      progressPercent: p(sundaySessions, 2),
      progressLabel: `${Math.min(sundaySessions, 2)} / 2 Sunday Sessions`,
    },
    {
      id: 'habit_monday',
      category: 'habits',
      title: 'Monday Antidote',
      subtitle: 'Defeating the Blues',
      description: 'Start your week with a victorious Monday game session.',
      tier: 'bronze',
      iconName: 'Zap',
      unlocked: mondaySessions >= 1,
      progressPercent: mondaySessions >= 1 ? 100 : 0,
      progressLabel: mondaySessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_midweek',
      category: 'habits',
      title: 'Hump Day Hero',
      subtitle: 'Midweek Recharge',
      description: 'Power through Wednesday with a logged gaming session.',
      tier: 'bronze',
      iconName: 'Target',
      unlocked: wednesdaySessions >= 1,
      progressPercent: wednesdaySessions >= 1 ? 100 : 0,
      progressLabel: wednesdaySessions >= 1 ? 'Unlocked' : 'Locked',
    },
    {
      id: 'habit_all_times',
      category: 'habits',
      title: 'Chrono Master',
      subtitle: '24-Hour Cycle',
      description: 'Play sessions across day, evening, and nocturnal time windows.',
      tier: 'gold',
      iconName: 'Compass',
      unlocked: morningSessions >= 1 && eveningSessions >= 1 && nightSessions >= 1,
      progressPercent:
        ((morningSessions >= 1 ? 1 : 0) +
          (eveningSessions >= 1 ? 1 : 0) +
          (nightSessions >= 1 ? 1 : 0)) *
        33,
      progressLabel: 'Day, Evening & Night',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 6. GENRE NOMAD & VARIETY (12 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'genre_2',
      category: 'genres',
      title: 'Dipping a Toe',
      subtitle: 'Dual Genres',
      description: 'Log active playtime across at least 2 distinct game genres.',
      tier: 'bronze',
      iconName: 'Compass',
      unlocked: genreCount >= 2,
      progressPercent: p(genreCount, 2),
      progressLabel: `${Math.min(genreCount, 2)} / 2 Genres`,
    },
    {
      id: 'genre_3',
      category: 'genres',
      title: 'Tasting Menu',
      subtitle: 'Diverse Palate',
      description: 'Experience gameplay across 3 different genres.',
      tier: 'bronze',
      iconName: 'Compass',
      unlocked: genreCount >= 3,
      progressPercent: p(genreCount, 3),
      progressLabel: `${Math.min(genreCount, 3)} / 3 Genres`,
    },
    {
      id: 'genre_5',
      category: 'genres',
      title: 'Genre Nomad',
      subtitle: 'Eclectic Taste',
      description: 'Explore and log playtime across at least 5 different game genres.',
      tier: 'silver',
      iconName: 'Compass',
      unlocked: genreCount >= 5,
      progressPercent: p(genreCount, 5),
      progressLabel: `${Math.min(genreCount, 5)} / 5 Genres`,
    },
    {
      id: 'genre_8',
      category: 'genres',
      title: 'Eclectic Polymath',
      subtitle: 'Eight Worlds Mastered',
      description: 'Expand your gameplay experience across 8 genres.',
      tier: 'gold',
      iconName: 'Compass',
      unlocked: genreCount >= 8,
      progressPercent: p(genreCount, 8),
      progressLabel: `${Math.min(genreCount, 8)} / 8 Genres`,
    },
    {
      id: 'genre_10',
      category: 'genres',
      title: 'Universal Player',
      subtitle: 'Master of All Realms',
      description: 'Log verified playtime across 10 or more game genres.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: genreCount >= 10,
      progressPercent: p(genreCount, 10),
      progressLabel: `${Math.min(genreCount, 10)} / 10 Genres`,
    },
    {
      id: 'genre_action',
      category: 'genres',
      title: 'Adrenaline Junkie',
      subtitle: 'Action Specialist',
      description: 'Invest 10+ hours into high-octane Action titles.',
      tier: 'silver',
      iconName: 'Swords',
      unlocked: genreHours('Action') >= 10,
      progressPercent: p(genreHours('Action'), 10),
      progressLabel: `${Math.min(genreHours('Action'), 10)} / 10 Hours`,
    },
    {
      id: 'genre_rpg',
      category: 'genres',
      title: 'Quest Hero',
      subtitle: 'Roleplay Devotee',
      description: 'Accumulate 10+ hours in deep RPG character journeys.',
      tier: 'silver',
      iconName: 'Shield',
      unlocked: genreHours('Role-playing') >= 10 || genreHours('RPG') >= 10,
      progressPercent: p(Math.max(genreHours('Role-playing'), genreHours('RPG')), 10),
      progressLabel: `${Math.min(Math.max(genreHours('Role-playing'), genreHours('RPG')), 10)} / 10 Hours`,
    },
    {
      id: 'genre_shooter',
      category: 'genres',
      title: 'Sharpshooter',
      subtitle: 'Ballistics Specialist',
      description: 'Spend 10+ hours in Shooter & FPS games.',
      tier: 'silver',
      iconName: 'Crosshair',
      unlocked: genreHours('Shooter') >= 10,
      progressPercent: p(genreHours('Shooter'), 10),
      progressLabel: `${Math.min(genreHours('Shooter'), 10)} / 10 Hours`,
    },
    {
      id: 'genre_strategy',
      category: 'genres',
      title: 'Grand Tactician',
      subtitle: 'Mastermind',
      description: 'Log 10+ hours plotting moves in Strategy & Tactics games.',
      tier: 'silver',
      iconName: 'Brain',
      unlocked: genreHours('Strategy') >= 10 || genreHours('Tactical') >= 10,
      progressPercent: p(Math.max(genreHours('Strategy'), genreHours('Tactical')), 10),
      progressLabel: `${Math.min(Math.max(genreHours('Strategy'), genreHours('Tactical')), 10)} / 10 Hours`,
    },
    {
      id: 'genre_adventure',
      category: 'genres',
      title: 'Intrepid Explorer',
      subtitle: 'Uncharted Territory',
      description: 'Log 10+ hours solving mysteries in Adventure titles.',
      tier: 'silver',
      iconName: 'MapPin',
      unlocked: genreHours('Adventure') >= 10,
      progressPercent: p(genreHours('Adventure'), 10),
      progressLabel: `${Math.min(genreHours('Adventure'), 10)} / 10 Hours`,
    },
    {
      id: 'genre_indie',
      category: 'genres',
      title: 'Indie Connoisseur',
      subtitle: 'Pure Artistry',
      description: 'Dedicate 10+ hours to creative Indie gems.',
      tier: 'silver',
      iconName: 'Heart',
      unlocked: genreHours('Indie') >= 10,
      progressPercent: p(genreHours('Indie'), 10),
      progressLabel: `${Math.min(genreHours('Indie'), 10)} / 10 Hours`,
    },
    {
      id: 'genre_simulation',
      category: 'genres',
      title: 'Reality Architect',
      subtitle: 'Simulation Pioneer',
      description: 'Spend 10+ hours building and piloting in Simulations.',
      tier: 'silver',
      iconName: 'Laptop',
      unlocked: genreHours('Simulator') >= 10 || genreHours('Simulation') >= 10,
      progressPercent: p(Math.max(genreHours('Simulator'), genreHours('Simulation')), 10),
      progressLabel: `${Math.min(Math.max(genreHours('Simulator'), genreHours('Simulation')), 10)} / 10 Hours`,
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 7. TITLE DEVOTION & MASTERY (12 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'devote_5h',
      category: 'devotion',
      title: 'First Attachment',
      subtitle: 'Getting Invested',
      description: 'Invest 5 hours into your top played game.',
      tier: 'bronze',
      iconName: 'Heart',
      unlocked: topGameHours >= 5,
      progressPercent: p(topGameHours, 5),
      progressLabel: `${Math.min(topGameHours, 5)} / 5 Hours`,
    },
    {
      id: 'devote_10h',
      category: 'devotion',
      title: 'True Enthusiast',
      subtitle: 'Double-Digit Bond',
      description: 'Reach 10 hours in a single game title.',
      tier: 'bronze',
      iconName: 'Heart',
      unlocked: topGameHours >= 10,
      progressPercent: p(topGameHours, 10),
      progressLabel: `${Math.min(topGameHours, 10)} / 10 Hours`,
    },
    {
      id: 'devote_20h',
      category: 'devotion',
      title: 'Campaign Veteran',
      subtitle: 'Credit Roll Territoriy',
      description: 'Play 20 hours in your favorite champion title.',
      tier: 'silver',
      iconName: 'Trophy',
      unlocked: topGameHours >= 20,
      progressPercent: p(topGameHours, 20),
      progressLabel: `${Math.min(topGameHours, 20)} / 20 Hours`,
    },
    {
      id: 'devote_35h',
      category: 'devotion',
      title: 'Main Game Syndrome',
      subtitle: 'Deep Connection',
      description: 'Accumulate 35 hours in a single primary title.',
      tier: 'silver',
      iconName: 'Flame',
      unlocked: topGameHours >= 35,
      progressPercent: p(topGameHours, 35),
      progressLabel: `${Math.min(topGameHours, 35)} / 35 Hours`,
    },
    {
      id: 'devote_50h',
      category: 'devotion',
      title: 'Dedicated Champion',
      subtitle: 'True Devotion',
      description: 'Invest over 50 hours of gameplay into a single champion title.',
      tier: 'gold',
      iconName: 'Trophy',
      unlocked: topGameHours >= 50,
      progressPercent: p(topGameHours, 50),
      progressLabel: `${Math.min(topGameHours, 50)} / 50 Hours`,
    },
    {
      id: 'devote_75h',
      category: 'devotion',
      title: 'Obsessed Specialist',
      subtitle: 'Elite Mastery',
      description: 'Reach 75 hours in your most played game.',
      tier: 'gold',
      iconName: 'Crown',
      unlocked: topGameHours >= 75,
      progressPercent: p(topGameHours, 75),
      progressLabel: `${Math.min(topGameHours, 75)} / 75 Hours`,
    },
    {
      id: 'devote_100h',
      category: 'devotion',
      title: 'Centurion of One',
      subtitle: 'Triple-Digit Single Game',
      description: 'Pour 100 hours into mastering a single masterpiece.',
      tier: 'gold',
      iconName: 'Crown',
      unlocked: topGameHours >= 100,
      progressPercent: p(topGameHours, 100),
      progressLabel: `${Math.min(topGameHours, 100)} / 100 Hours`,
    },
    {
      id: 'devote_200h',
      category: 'devotion',
      title: 'Single-Title Monarch',
      subtitle: '200 Hours in One World',
      description: 'Dedicate 200 hours to your primary title.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: topGameHours >= 200,
      progressPercent: p(topGameHours, 200),
      progressLabel: `${Math.min(topGameHours, 200)} / 200 Hours`,
    },
    {
      id: 'devote_300h',
      category: 'devotion',
      title: 'The Eternal Obsession',
      subtitle: '300-Hour Pillar',
      description: 'Achieve 300 hours in a single game.',
      tier: 'platinum',
      iconName: 'Trophy',
      unlocked: topGameHours >= 300,
      progressPercent: p(topGameHours, 300),
      progressLabel: `${Math.min(topGameHours, 300)} / 300 Hours`,
    },
    {
      id: 'devote_500h',
      category: 'devotion',
      title: 'Transcendent Master',
      subtitle: '500-Hour Zenith',
      description: 'Cross the 500-hour boundary in one singular game.',
      tier: 'platinum',
      iconName: 'Sparkles',
      unlocked: topGameHours >= 500,
      progressPercent: p(topGameHours, 500),
      progressLabel: `${Math.min(topGameHours, 500)} / 500 Hours`,
    },
    {
      id: 'devote_50pct',
      category: 'devotion',
      title: 'Singular Focus',
      subtitle: 'Top Game Dominance',
      description: 'Your favorite title represents more than 50% of your total library playtime.',
      tier: 'silver',
      iconName: 'Target',
      unlocked: totalSeconds > 0 && topGameSeconds / totalSeconds >= 0.5,
      progressPercent:
        totalSeconds > 0 ? Math.min(100, Math.round((topGameSeconds / totalSeconds) * 200)) : 0,
      progressLabel:
        totalSeconds > 0
          ? `${Math.round((topGameSeconds / totalSeconds) * 100)}% / 50%`
          : '0% / 50%',
    },
    {
      id: 'devote_diverse',
      category: 'devotion',
      title: 'Balanced Palette',
      subtitle: 'Democratic Player',
      description: 'Your top game represents less than 35% of your playtime across 5+ games.',
      tier: 'silver',
      iconName: 'Award',
      unlocked: totalGames >= 5 && totalSeconds > 0 && topGameSeconds / totalSeconds < 0.35,
      progressPercent:
        totalGames >= 5 && totalSeconds > 0 && topGameSeconds / totalSeconds < 0.35 ? 100 : 0,
      progressLabel: totalGames >= 5 ? 'Balanced Library' : `${totalGames} / 5 Games`,
    },

    // ══════════════════════════════════════════════════════════════════════════
    // 8. CURATION & SYSTEM MASTERY (8 Milestones)
    // ══════════════════════════════════════════════════════════════════════════
    {
      id: 'master_played_all',
      category: 'mastery',
      title: 'No Backlog Left Behind',
      subtitle: 'Zero Guilt',
      description: 'Play at least 70% of the games in your collection.',
      tier: 'gold',
      iconName: 'CheckCircle2',
      unlocked: totalGames >= 3 && playedGamesCount / totalGames >= 0.7,
      progressPercent: totalGames > 0 ? p(playedGamesCount, Math.ceil(totalGames * 0.7)) : 0,
      progressLabel: `${playedGamesCount} / ${totalGames} Played`,
    },
    {
      id: 'master_tagged',
      category: 'mastery',
      title: 'Taxonomy Specialist',
      subtitle: 'Organized Mind',
      description: 'Categorize at least 3 games using custom tags.',
      tier: 'bronze',
      iconName: 'Tag',
      unlocked: taggedGamesCount >= 3,
      progressPercent: p(taggedGamesCount, 3),
      progressLabel: `${Math.min(taggedGamesCount, 3)} / 3 Tagged`,
    },
    {
      id: 'master_custom_art',
      category: 'mastery',
      title: 'Gallery Curator',
      subtitle: 'Aesthetic Perfection',
      description: 'Set custom cover artwork for 5 or more games.',
      tier: 'bronze',
      iconName: 'Image',
      unlocked: customCoverCount >= 5,
      progressPercent: p(customCoverCount, 5),
      progressLabel: `${Math.min(customCoverCount, 5)} / 5 Games with Art`,
    },
    {
      id: 'master_multi_install',
      category: 'mastery',
      title: 'Ready for Anything',
      subtitle: 'Triple Installation',
      description: 'Maintain 3 or more installed games simultaneously.',
      tier: 'silver',
      iconName: 'HardDrive',
      unlocked: installedGames >= 3,
      progressPercent: p(installedGames, 3),
      progressLabel: `${Math.min(installedGames, 3)} / 3 Ready`,
    },
    {
      id: 'master_clean_vault',
      category: 'mastery',
      title: 'Pristine Vault',
      subtitle: 'Zero Broken Links',
      description: 'All installed games have validated launch executables.',
      tier: 'silver',
      iconName: 'ShieldCheck',
      unlocked: installedGames >= 2,
      progressPercent: p(installedGames, 2),
      progressLabel: `${Math.min(installedGames, 2)} / 2 Verified`,
    },
    {
      id: 'master_double_century',
      category: 'mastery',
      title: 'Vault Luminary',
      subtitle: 'Elite Veteran',
      description: 'Accumulate 200+ total hours and own at least 10 titles.',
      tier: 'gold',
      iconName: 'Sparkles',
      unlocked: totalHours >= 200 && totalGames >= 10,
      progressPercent: Math.min(p(totalHours, 200), p(totalGames, 10)),
      progressLabel: `${totalHours}h / 200h & ${totalGames}/10 Games`,
    },
    {
      id: 'master_grand_slam',
      category: 'mastery',
      title: 'The Triple Crown',
      subtitle: '50h + 10 Games + 7d Streak',
      description: 'Achieve 50 hours of playtime, 10 games in vault, and a 7-day streak.',
      tier: 'platinum',
      iconName: 'Trophy',
      unlocked: totalHours >= 50 && totalGames >= 10 && streak >= 7,
      progressPercent: Math.min(p(totalHours, 50), p(totalGames, 10), p(streak, 7)),
      progressLabel: `${totalHours}h, ${totalGames}g, ${streak}d`,
    },
    {
      id: 'master_nexus_prime',
      category: 'mastery',
      title: 'Nexus Prime Sovereign',
      subtitle: 'The Half-Century Milestone',
      description: 'Unlock 25 or more achievement trophies across any category.',
      tier: 'platinum',
      iconName: 'Crown',
      unlocked: false, // Calculated dynamically below
      progressPercent: 0,
      progressLabel: '0 / 25 Unlocked',
    },
  ]

  // Calculate master_nexus_prime dynamically based on preceding unlocked milestones
  const unlockedExceptLast = milestones.slice(0, -1).filter((m) => m.unlocked).length
  const lastIndex = milestones.length - 1
  milestones[lastIndex] = {
    ...milestones[lastIndex],
    unlocked: unlockedExceptLast >= 25,
    progressPercent: p(unlockedExceptLast, 25),
    progressLabel: `${Math.min(unlockedExceptLast, 25)} / 25 Trophies`,
  }

  return milestones
}
