import type { FullThemeConfig } from './theme-tokens'

export const THEME_REGISTRY: Record<string, FullThemeConfig> = {
  // ==========================================
  // 1. ICONIC GAMING
  // ==========================================
  cyberpunk: {
    definition: {
      id: 'cyberpunk',
      name: 'Cyberpunk 2077',
      category: 'iconic',
      description: 'High-contrast neon yellow & glitch cyan with chamfered angular edges.',
      layout: 'modular-cards',
      previewGradient: 'from-yellow-400 via-amber-500 to-cyan-500',
      accentColor: '#fcee0a',
      tags: ['Neon', 'Chamfered', 'Glitch', 'High Contrast'],
    },
    tokens: {
      fontFamily: 'font-mono tracking-tight',
      bgStyle: 'bg-zinc-950/90 border border-yellow-400/80 shadow-[0_0_20px_rgba(252,238,10,0.25)]',
      borderStyle: 'border-yellow-400/80',
      accentColor: '#fcee0a',
      primaryTextColor: 'text-yellow-300 font-bold',
      secondaryTextColor: 'text-cyan-400',
      warningColor: '#ff003c',
      dangerColor: '#ff0055',
      graphLineColor: '#fcee0a',
      graphFillColor: 'rgba(252, 238, 10, 0.15)',
      cornerStyle: 'chamfered',
    },
  },

  afterburner: {
    definition: {
      id: 'afterburner',
      name: 'MSI Afterburner',
      category: 'iconic',
      description: 'Classic enthusiast telemetry HUD with bright safety orange and dense readout.',
      layout: 'vertical-strip',
      previewGradient: 'from-orange-500 via-amber-600 to-zinc-900',
      accentColor: '#ff6600',
      tags: ['Classic', 'Dense', 'Orange', 'Enthusiast'],
    },
    tokens: {
      fontFamily: 'font-mono tracking-tighter',
      bgStyle: 'bg-black/92 border border-orange-500/60 shadow-[0_4px_24px_rgba(255,102,0,0.2)]',
      borderStyle: 'border-orange-500/60',
      accentColor: '#ff6600',
      primaryTextColor: 'text-orange-400 font-semibold',
      secondaryTextColor: 'text-zinc-400',
      warningColor: '#f59e0b',
      dangerColor: '#ef4444',
      graphLineColor: '#ff6600',
      graphFillColor: 'rgba(255, 102, 0, 0.2)',
      cornerStyle: 'sharp',
    },
  },

  adrenalin: {
    definition: {
      id: 'adrenalin',
      name: 'Radeon Adrenalin',
      category: 'iconic',
      description: 'Crimson red accents on brushed dark titanium card with prominent FPS meter.',
      layout: 'modular-cards',
      previewGradient: 'from-red-600 via-rose-600 to-zinc-900',
      accentColor: '#e60026',
      tags: ['Radeon', 'Red', 'Sleek', 'Card'],
    },
    tokens: {
      fontFamily: 'font-sans tracking-wide',
      bgStyle: 'bg-zinc-950/92 border border-red-600/70 shadow-[0_0_25px_rgba(230,0,38,0.25)]',
      borderStyle: 'border-red-600/70',
      accentColor: '#e60026',
      primaryTextColor: 'text-red-400 font-bold',
      secondaryTextColor: 'text-zinc-300',
      warningColor: '#fbbf24',
      dangerColor: '#dc2626',
      graphLineColor: '#e60026',
      graphFillColor: 'rgba(230, 0, 38, 0.18)',
      cornerStyle: 'rounded',
    },
  },

  geforce: {
    definition: {
      id: 'geforce',
      name: 'GeForce Experience',
      category: 'iconic',
      description: 'Signature vibrant lime green telemetry on matte dark slate background.',
      layout: 'modular-cards',
      previewGradient: 'from-emerald-500 via-green-600 to-zinc-950',
      accentColor: '#76b900',
      tags: ['GeForce', 'Green', 'Clean', 'Modern'],
    },
    tokens: {
      fontFamily: 'font-sans font-medium',
      bgStyle: 'bg-zinc-900/90 border border-lime-500/60 shadow-[0_0_20px_rgba(118,185,0,0.2)]',
      borderStyle: 'border-lime-500/60',
      accentColor: '#76b900',
      primaryTextColor: 'text-lime-400 font-bold',
      secondaryTextColor: 'text-zinc-200',
      warningColor: '#f59e0b',
      dangerColor: '#ef4444',
      graphLineColor: '#76b900',
      graphFillColor: 'rgba(118, 185, 0, 0.15)',
      cornerStyle: 'rounded',
    },
  },

  mangohud: {
    definition: {
      id: 'mangohud',
      name: 'MangoHud Ultra',
      category: 'iconic',
      description: 'Translucent horizontal pill bar with color-coded multi-core telemetry.',
      layout: 'horizontal-bar',
      previewGradient: 'from-teal-400 via-emerald-500 to-zinc-900',
      accentColor: '#2dd4bf',
      tags: ['Linux', 'Compact', 'Horizontal', 'Teal'],
    },
    tokens: {
      fontFamily: 'font-mono text-sm',
      bgStyle: 'bg-black/85 border border-zinc-700/60 shadow-lg backdrop-blur-sm',
      borderStyle: 'border-zinc-700/60',
      accentColor: '#2dd4bf',
      primaryTextColor: 'text-teal-300 font-bold',
      secondaryTextColor: 'text-zinc-300',
      warningColor: '#eab308',
      dangerColor: '#f43f5e',
      graphLineColor: '#2dd4bf',
      graphFillColor: 'rgba(45, 212, 191, 0.15)',
      cornerStyle: 'pill',
    },
  },

  steam_deck: {
    definition: {
      id: 'steam_deck',
      name: 'Steam Deck L4',
      category: 'iconic',
      description:
        'Level 4 Performance Overlay recreation with soft pill badges and battery metrics.',
      layout: 'modular-cards',
      previewGradient: 'from-sky-400 via-blue-500 to-indigo-950',
      accentColor: '#38bdf8',
      tags: ['Handheld', 'Level 4', 'Battery', 'Clean'],
    },
    tokens: {
      fontFamily: 'font-sans font-semibold',
      bgStyle: 'bg-zinc-900/94 border border-sky-400/40 shadow-xl rounded-2xl',
      borderStyle: 'border-sky-400/40',
      accentColor: '#38bdf8',
      primaryTextColor: 'text-sky-300 font-bold',
      secondaryTextColor: 'text-zinc-100',
      warningColor: '#fbbf24',
      dangerColor: '#f87171',
      graphLineColor: '#38bdf8',
      graphFillColor: 'rgba(56, 189, 248, 0.18)',
      cornerStyle: 'pill',
    },
  },

  // ==========================================
  // 2. CLEAN & MODERN
  // ==========================================
  frosted_glass: {
    definition: {
      id: 'frosted_glass',
      name: 'Frosted Glass',
      category: 'modern',
      description: 'Ultra-refined translucent acrylic card with soft hairline borders.',
      layout: 'modular-cards',
      previewGradient: 'from-white/30 via-slate-400/20 to-zinc-900',
      accentColor: '#ffffff',
      tags: ['Glassmorphism', 'Minimal', 'Acrylic', 'Soft'],
    },
    tokens: {
      fontFamily: 'font-sans font-light',
      bgStyle:
        'bg-white/10 border border-white/20 shadow-[0_8px_32px_rgba(0,0,0,0.37)] backdrop-blur-md',
      borderStyle: 'border-white/20',
      accentColor: '#ffffff',
      primaryTextColor: 'text-white font-medium',
      secondaryTextColor: 'text-zinc-300',
      warningColor: '#fde047',
      dangerColor: '#f87171',
      graphLineColor: '#ffffff',
      graphFillColor: 'rgba(255, 255, 255, 0.1)',
      cornerStyle: 'rounded',
    },
  },

  minimal_horizon: {
    definition: {
      id: 'minimal_horizon',
      name: 'Minimal Horizon',
      category: 'modern',
      description: 'Single-line edge docked strip with elegant hairline micro-dividers.',
      layout: 'horizontal-bar',
      previewGradient: 'from-zinc-700 via-zinc-800 to-black',
      accentColor: '#a1a1aa',
      tags: ['Ultra Minimal', 'Single Line', 'Zero Clutter'],
    },
    tokens: {
      fontFamily: 'font-mono text-xs',
      bgStyle: 'bg-zinc-950/80 border-b border-zinc-800 shadow-md',
      borderStyle: 'border-zinc-800',
      accentColor: '#e4e4e7',
      primaryTextColor: 'text-zinc-100 font-semibold',
      secondaryTextColor: 'text-zinc-400',
      warningColor: '#eab308',
      dangerColor: '#ef4444',
      graphLineColor: '#a1a1aa',
      graphFillColor: 'rgba(161, 161, 170, 0.1)',
      cornerStyle: 'sharp',
    },
  },

  oled_stealth: {
    definition: {
      id: 'oled_stealth',
      name: 'OLED Stealth',
      category: 'modern',
      description:
        'Pitch black backdrop with dim silver text to preserve OLED panels and reduce eye strain.',
      layout: 'vertical-strip',
      previewGradient: 'from-zinc-800 to-black',
      accentColor: '#94a3b8',
      tags: ['OLED', 'Battery Saver', 'Stealth', 'Dim'],
    },
    tokens: {
      fontFamily: 'font-mono',
      bgStyle: 'bg-black border border-zinc-800/80',
      borderStyle: 'border-zinc-800/80',
      accentColor: '#94a3b8',
      primaryTextColor: 'text-zinc-200 font-medium',
      secondaryTextColor: 'text-zinc-500',
      warningColor: '#ca8a04',
      dangerColor: '#dc2626',
      graphLineColor: '#64748b',
      graphFillColor: 'rgba(100, 116, 139, 0.1)',
      cornerStyle: 'sharp',
    },
  },

  monolith: {
    definition: {
      id: 'monolith',
      name: 'Monolith Architectural',
      category: 'modern',
      description: 'Solid dark slab with architectural typography and warm amber micro-accents.',
      layout: 'vertical-strip',
      previewGradient: 'from-stone-700 via-stone-800 to-zinc-950',
      accentColor: '#d97706',
      tags: ['Architectural', 'Solid', 'Warm Amber', 'Typography'],
    },
    tokens: {
      fontFamily: 'font-sans tracking-tight',
      bgStyle: 'bg-stone-950/95 border-l-2 border-amber-500 shadow-2xl',
      borderStyle: 'border-stone-800',
      accentColor: '#d97706',
      primaryTextColor: 'text-amber-400 font-semibold',
      secondaryTextColor: 'text-stone-300',
      warningColor: '#f59e0b',
      dangerColor: '#b91c1c',
      graphLineColor: '#d97706',
      graphFillColor: 'rgba(217, 119, 6, 0.15)',
      cornerStyle: 'sharp',
    },
  },

  carbon_titanium: {
    definition: {
      id: 'carbon_titanium',
      name: 'Carbon Titanium',
      category: 'modern',
      description:
        'Textured carbon fiber with brushed metallic titanium borders and steel blue hues.',
      layout: 'modular-cards',
      previewGradient: 'from-slate-600 via-zinc-800 to-zinc-950',
      accentColor: '#60a5fa',
      tags: ['Carbon', 'Titanium', 'Metallic', 'Automotive'],
    },
    tokens: {
      fontFamily: 'font-mono',
      bgStyle: 'bg-zinc-950/92 border border-slate-600/50 shadow-[0_10px_30px_rgba(0,0,0,0.5)]',
      borderStyle: 'border-slate-600/50',
      accentColor: '#60a5fa',
      primaryTextColor: 'text-blue-300 font-bold',
      secondaryTextColor: 'text-slate-300',
      warningColor: '#f59e0b',
      dangerColor: '#ef4444',
      graphLineColor: '#60a5fa',
      graphFillColor: 'rgba(96, 165, 250, 0.15)',
      cornerStyle: 'rounded',
    },
  },

  // ==========================================
  // 3. SCI-FI & FUTURISTIC
  // ==========================================
  spaceship_cockpit: {
    definition: {
      id: 'spaceship_cockpit',
      name: 'Cockpit Flight HUD',
      category: 'scifi',
      description:
        'Flight simulation telemetry with angled targeting brackets and cyan vector guides.',
      layout: 'bracket-hud',
      previewGradient: 'from-cyan-400 via-teal-500 to-blue-950',
      accentColor: '#00f0ff',
      tags: ['Space', 'Flight', 'Targeting', 'Brackets'],
    },
    tokens: {
      fontFamily: 'font-mono uppercase tracking-widest',
      bgStyle:
        'bg-zinc-950/80 border-t-2 border-b-2 border-cyan-400/80 shadow-[0_0_20px_rgba(0,240,255,0.2)]',
      borderStyle: 'border-cyan-400/60',
      accentColor: '#00f0ff',
      primaryTextColor: 'text-cyan-300 font-bold',
      secondaryTextColor: 'text-cyan-100/70',
      warningColor: '#eab308',
      dangerColor: '#f43f5e',
      graphLineColor: '#00f0ff',
      graphFillColor: 'rgba(0, 240, 255, 0.15)',
      cornerStyle: 'chamfered',
    },
  },

  arc_reactor: {
    definition: {
      id: 'arc_reactor',
      name: 'Arc Reactor Core',
      category: 'scifi',
      description:
        'Stark Industries energy core aesthetic with circular power rings and blue plasma glow.',
      layout: 'radial-gauges',
      previewGradient: 'from-sky-400 via-cyan-500 to-blue-900',
      accentColor: '#0ea5e9',
      tags: ['Plasma', 'Energy', 'Blue Glow', 'Core'],
    },
    tokens: {
      fontFamily: 'font-sans font-bold',
      bgStyle: 'bg-slate-950/90 border border-sky-400/60 shadow-[0_0_30px_rgba(14,165,233,0.3)]',
      borderStyle: 'border-sky-400/60',
      accentColor: '#0ea5e9',
      primaryTextColor: 'text-sky-300 font-extrabold',
      secondaryTextColor: 'text-cyan-200',
      warningColor: '#f59e0b',
      dangerColor: '#ef4444',
      graphLineColor: '#0ea5e9',
      graphFillColor: 'rgba(14, 165, 233, 0.2)',
      cornerStyle: 'pill',
    },
  },

  quantum_core: {
    definition: {
      id: 'quantum_core',
      name: 'Quantum Core',
      category: 'scifi',
      description: 'Deep violet quantum plasma telemetry with ultraviolet luminescence.',
      layout: 'modular-cards',
      previewGradient: 'from-violet-500 via-purple-600 to-indigo-950',
      accentColor: '#a855f7',
      tags: ['Quantum', 'Violet', 'Purple', 'Plasma'],
    },
    tokens: {
      fontFamily: 'font-mono tracking-tight',
      bgStyle: 'bg-zinc-950/92 border border-purple-500/70 shadow-[0_0_25px_rgba(168,85,247,0.25)]',
      borderStyle: 'border-purple-500/70',
      accentColor: '#a855f7',
      primaryTextColor: 'text-purple-300 font-bold',
      secondaryTextColor: 'text-violet-200',
      warningColor: '#f59e0b',
      dangerColor: '#ef4444',
      graphLineColor: '#a855f7',
      graphFillColor: 'rgba(168, 85, 247, 0.2)',
      cornerStyle: 'rounded',
    },
  },

  holo_circular: {
    definition: {
      id: 'holo_circular',
      name: 'Holographic Projection',
      category: 'scifi',
      description: 'Futuristic floating holographic ring HUD with transparent glass feel.',
      layout: 'radial-gauges',
      previewGradient: 'from-teal-300 via-cyan-400 to-blue-900',
      accentColor: '#22d3ee',
      tags: ['Holo', 'Rings', 'Floating', 'Futuristic'],
    },
    tokens: {
      fontFamily: 'font-sans uppercase tracking-widest',
      bgStyle:
        'bg-cyan-950/40 border border-cyan-400/40 backdrop-blur-md shadow-[0_0_20px_rgba(34,211,238,0.25)]',
      borderStyle: 'border-cyan-400/40',
      accentColor: '#22d3ee',
      primaryTextColor: 'text-cyan-200 font-bold',
      secondaryTextColor: 'text-cyan-400/80',
      warningColor: '#fbbf24',
      dangerColor: '#f43f5e',
      graphLineColor: '#22d3ee',
      graphFillColor: 'rgba(34, 211, 238, 0.15)',
      cornerStyle: 'pill',
    },
  },

  solar_flare: {
    definition: {
      id: 'solar_flare',
      name: 'Solar Flare Plasma',
      category: 'scifi',
      description:
        'Radiant golden plasma with high-temperature color grading and burning amber glow.',
      layout: 'modular-cards',
      previewGradient: 'from-amber-400 via-orange-500 to-red-900',
      accentColor: '#f59e0b',
      tags: ['Solar', 'Golden', 'Plasma', 'Warm'],
    },
    tokens: {
      fontFamily: 'font-mono font-bold',
      bgStyle: 'bg-zinc-950/92 border border-amber-500/70 shadow-[0_0_25px_rgba(245,158,11,0.25)]',
      borderStyle: 'border-amber-500/70',
      accentColor: '#f59e0b',
      primaryTextColor: 'text-amber-300 font-extrabold',
      secondaryTextColor: 'text-orange-200',
      warningColor: '#fbbf24',
      dangerColor: '#ef4444',
      graphLineColor: '#f59e0b',
      graphFillColor: 'rgba(245, 158, 11, 0.2)',
      cornerStyle: 'rounded',
    },
  },

  // ==========================================
  // 4. RETRO & SYNTH
  // ==========================================
  retro_synthwave: {
    definition: {
      id: 'retro_synthwave',
      name: 'Retro Synthwave 84',
      category: 'retro',
      description: 'Electric hot pink and neon purple neon grid with vibrant 80s nostalgia.',
      layout: 'modular-cards',
      previewGradient: 'from-fuchsia-500 via-pink-600 to-indigo-950',
      accentColor: '#ec4899',
      tags: ['80s', 'Synthwave', 'Hot Pink', 'Outrun'],
    },
    tokens: {
      fontFamily: 'font-mono italic tracking-wide',
      bgStyle: 'bg-zinc-950/92 border border-pink-500/80 shadow-[0_0_25px_rgba(236,72,153,0.3)]',
      borderStyle: 'border-pink-500/80',
      accentColor: '#ec4899',
      primaryTextColor: 'text-pink-400 font-extrabold',
      secondaryTextColor: 'text-cyan-300',
      warningColor: '#fde047',
      dangerColor: '#ef4444',
      graphLineColor: '#ec4899',
      graphFillColor: 'rgba(236, 72, 153, 0.2)',
      cornerStyle: 'rounded',
      scanlines: true,
    },
  },

  arcade_crt: {
    definition: {
      id: 'arcade_crt',
      name: 'Arcade CRT Phosphor',
      category: 'retro',
      description: 'Phosphor green CRT monitor glow with retro scanline pixel styling.',
      layout: 'bracket-hud',
      previewGradient: 'from-green-500 via-emerald-600 to-zinc-950',
      accentColor: '#22c55e',
      tags: ['CRT', 'Arcade', 'Phosphor Green', 'Scanlines'],
    },
    tokens: {
      fontFamily: 'font-mono tracking-widest',
      bgStyle: 'bg-black/95 border-2 border-green-500/70 shadow-[0_0_20px_rgba(34,197,94,0.3)]',
      borderStyle: 'border-green-500/70',
      accentColor: '#22c55e',
      primaryTextColor: 'text-green-400 font-bold',
      secondaryTextColor: 'text-emerald-300/80',
      warningColor: '#facc15',
      dangerColor: '#f87171',
      graphLineColor: '#22c55e',
      graphFillColor: 'rgba(34, 197, 94, 0.2)',
      cornerStyle: 'chamfered',
      scanlines: true,
    },
  },

  vaporwave: {
    definition: {
      id: 'vaporwave',
      name: 'Vaporwave Windows 95',
      category: 'retro',
      description: 'Pastel magenta and soothing turquoise evoking 90s digital dreams.',
      layout: 'modular-cards',
      previewGradient: 'from-rose-400 via-teal-300 to-indigo-900',
      accentColor: '#f43f5e',
      tags: ['Pastel', '90s', 'Aesthetic', 'Turquoise'],
    },
    tokens: {
      fontFamily: 'font-mono',
      bgStyle: 'bg-slate-950/88 border border-rose-400/60 shadow-[0_0_20px_rgba(244,63,94,0.25)]',
      borderStyle: 'border-rose-400/60',
      accentColor: '#f43f5e',
      primaryTextColor: 'text-rose-300 font-bold',
      secondaryTextColor: 'text-teal-300',
      warningColor: '#fde047',
      dangerColor: '#ef4444',
      graphLineColor: '#f43f5e',
      graphFillColor: 'rgba(244, 63, 94, 0.15)',
      cornerStyle: 'rounded',
      scanlines: true,
    },
  },

  matrix: {
    definition: {
      id: 'matrix',
      name: 'Matrix Digital Rain',
      category: 'retro',
      description: 'Deep black terminal with vibrant glowing matrix green data streams.',
      layout: 'vertical-strip',
      previewGradient: 'from-lime-500 via-green-600 to-black',
      accentColor: '#10b981',
      tags: ['Matrix', 'Terminal', 'Digital Rain', 'Green'],
    },
    tokens: {
      fontFamily: 'font-mono tracking-tighter',
      bgStyle: 'bg-black/95 border-l-2 border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.2)]',
      borderStyle: 'border-emerald-900',
      accentColor: '#10b981',
      primaryTextColor: 'text-emerald-400 font-semibold',
      secondaryTextColor: 'text-emerald-600',
      warningColor: '#eab308',
      dangerColor: '#ef4444',
      graphLineColor: '#10b981',
      graphFillColor: 'rgba(16, 185, 129, 0.2)',
      cornerStyle: 'sharp',
      scanlines: true,
    },
  },

  terminal_cli: {
    definition: {
      id: 'terminal_cli',
      name: 'UNIX Amber Terminal',
      category: 'retro',
      description: 'Classic monochrome amber VT100 console typography with bracketed headers.',
      layout: 'vertical-strip',
      previewGradient: 'from-amber-500 to-black',
      accentColor: '#f59e0b',
      tags: ['Amber', 'CLI', 'UNIX', 'Monochrome'],
    },
    tokens: {
      fontFamily: 'font-mono',
      bgStyle: 'bg-black/96 border border-amber-600/50 shadow-none',
      borderStyle: 'border-amber-600/50',
      accentColor: '#f59e0b',
      primaryTextColor: 'text-amber-500 font-bold',
      secondaryTextColor: 'text-amber-600/80',
      warningColor: '#fcd34d',
      dangerColor: '#dc2626',
      graphLineColor: '#f59e0b',
      graphFillColor: 'rgba(245, 158, 11, 0.1)',
      cornerStyle: 'sharp',
      scanlines: true,
    },
  },

  // ==========================================
  // 5. ESPORTS & COMPACT
  // ==========================================
  apex_tactical: {
    definition: {
      id: 'apex_tactical',
      name: 'Apex Tactical Military',
      category: 'esports',
      description: 'Military combat HUD with tactical yellow callsign tags and angular brackets.',
      layout: 'bracket-hud',
      previewGradient: 'from-yellow-400 via-amber-600 to-stone-900',
      accentColor: '#eab308',
      tags: ['Military', 'Tactical', 'Apex', 'Yellow'],
    },
    tokens: {
      fontFamily: 'font-mono uppercase font-black',
      bgStyle: 'bg-stone-950/90 border-r-4 border-yellow-400 shadow-xl',
      borderStyle: 'border-stone-700',
      accentColor: '#eab308',
      primaryTextColor: 'text-yellow-400 font-black',
      secondaryTextColor: 'text-stone-300',
      warningColor: '#f97316',
      dangerColor: '#ef4444',
      graphLineColor: '#eab308',
      graphFillColor: 'rgba(234, 179, 8, 0.2)',
      cornerStyle: 'chamfered',
    },
  },

  forza_telemetry: {
    definition: {
      id: 'forza_telemetry',
      name: 'Forza Motorsport',
      category: 'esports',
      description: 'High-speed motorsport telemetry with redline tachometer accent curves.',
      layout: 'modular-cards',
      previewGradient: 'from-red-500 via-orange-500 to-zinc-950',
      accentColor: '#ef4444',
      tags: ['Racing', 'Motorsport', 'Redline', 'Speed'],
    },
    tokens: {
      fontFamily: 'font-mono italic font-bold',
      bgStyle: 'bg-zinc-950/92 border-b-2 border-red-500 shadow-xl',
      borderStyle: 'border-zinc-800',
      accentColor: '#ef4444',
      primaryTextColor: 'text-red-400 font-extrabold',
      secondaryTextColor: 'text-zinc-200',
      warningColor: '#f59e0b',
      dangerColor: '#b91c1c',
      graphLineColor: '#ef4444',
      graphFillColor: 'rgba(239, 68, 68, 0.2)',
      cornerStyle: 'rounded',
    },
  },

  esports_pro: {
    definition: {
      id: 'esports_pro',
      name: 'Esports Championship',
      category: 'esports',
      description: 'Broadcast-grade tournament graphics with vivid cyan & magenta team badges.',
      layout: 'modular-cards',
      previewGradient: 'from-cyan-400 via-fuchsia-500 to-indigo-950',
      accentColor: '#06b6d4',
      tags: ['Broadcast', 'Tournament', 'Pro', 'Vivid'],
    },
    tokens: {
      fontFamily: 'font-sans font-black tracking-tight',
      bgStyle: 'bg-zinc-950/92 border-t-2 border-cyan-400 shadow-2xl',
      borderStyle: 'border-zinc-800',
      accentColor: '#06b6d4',
      primaryTextColor: 'text-cyan-300 font-extrabold',
      secondaryTextColor: 'text-fuchsia-300',
      warningColor: '#facc15',
      dangerColor: '#ef4444',
      graphLineColor: '#06b6d4',
      graphFillColor: 'rgba(6, 182, 212, 0.2)',
      cornerStyle: 'rounded',
    },
  },

  corner_mini: {
    definition: {
      id: 'corner_mini',
      name: 'Corner Mini-Badge',
      category: 'esports',
      description: 'Microscopic unobtrusive corner badge displaying critical FPS & Frametime only.',
      layout: 'compact-badge',
      previewGradient: 'from-zinc-700 to-zinc-900',
      accentColor: '#38bdf8',
      tags: ['Ultra Small', 'Corner', 'Micro', 'FPS Only'],
    },
    tokens: {
      fontFamily: 'font-mono text-xs font-bold',
      bgStyle: 'bg-black/80 border border-zinc-700/50 rounded-lg p-1.5 shadow',
      borderStyle: 'border-zinc-700/50',
      accentColor: '#38bdf8',
      primaryTextColor: 'text-sky-400 font-bold',
      secondaryTextColor: 'text-zinc-400',
      warningColor: '#fbbf24',
      dangerColor: '#f87171',
      graphLineColor: '#38bdf8',
      graphFillColor: 'rgba(56, 189, 248, 0.1)',
      cornerStyle: 'rounded',
    },
  },

  docked_strip: {
    definition: {
      id: 'docked_strip',
      name: 'Docked Edge Strip',
      category: 'esports',
      description: 'Snaps directly against your screen edge with seamless horizontal metrics flow.',
      layout: 'horizontal-bar',
      previewGradient: 'from-indigo-600 via-blue-600 to-zinc-900',
      accentColor: '#6366f1',
      tags: ['Docked', 'Bezel', 'Edge', 'Strip'],
    },
    tokens: {
      fontFamily: 'font-sans font-semibold text-xs',
      bgStyle: 'bg-zinc-950/90 border-b border-indigo-500/50 shadow-md backdrop-blur',
      borderStyle: 'border-indigo-500/50',
      accentColor: '#6366f1',
      primaryTextColor: 'text-indigo-300 font-bold',
      secondaryTextColor: 'text-zinc-300',
      warningColor: '#f59e0b',
      dangerColor: '#ef4444',
      graphLineColor: '#6366f1',
      graphFillColor: 'rgba(99, 102, 241, 0.15)',
      cornerStyle: 'sharp',
    },
  },

  // ==========================================
  // 6. THEMATIC & ARTISTIC
  // ==========================================
  cyber_samurai: {
    definition: {
      id: 'cyber_samurai',
      name: 'Cyber Samurai Ghost',
      category: 'thematic',
      description: 'Blood crimson katana slash aesthetic mixed with golden imperial gilding.',
      layout: 'bracket-hud',
      previewGradient: 'from-rose-600 via-red-700 to-amber-700',
      accentColor: '#e11d48',
      tags: ['Katana', 'Crimson', 'Gold', 'Samurai'],
    },
    tokens: {
      fontFamily: 'font-mono uppercase font-bold',
      bgStyle: 'bg-zinc-950/94 border-l-4 border-rose-600 shadow-[0_0_25px_rgba(225,29,72,0.3)]',
      borderStyle: 'border-zinc-800',
      accentColor: '#e11d48',
      primaryTextColor: 'text-rose-400 font-extrabold',
      secondaryTextColor: 'text-amber-300',
      warningColor: '#f59e0b',
      dangerColor: '#9f1239',
      graphLineColor: '#e11d48',
      graphFillColor: 'rgba(225, 29, 72, 0.2)',
      cornerStyle: 'chamfered',
    },
  },

  nordic_frost: {
    definition: {
      id: 'nordic_frost',
      name: 'Nordic Glacial Frost',
      category: 'thematic',
      description: 'Glacial ice cyan and blizzard crystal white with chilled crystalline aura.',
      layout: 'modular-cards',
      previewGradient: 'from-cyan-300 via-sky-400 to-slate-900',
      accentColor: '#38bdf8',
      tags: ['Ice', 'Frost', 'Blizzard', 'Cold Cyan'],
    },
    tokens: {
      fontFamily: 'font-sans font-light tracking-wide',
      bgStyle:
        'bg-slate-950/85 border border-cyan-300/50 shadow-[0_0_20px_rgba(56,189,248,0.25)] backdrop-blur-md',
      borderStyle: 'border-cyan-300/50',
      accentColor: '#38bdf8',
      primaryTextColor: 'text-cyan-200 font-medium',
      secondaryTextColor: 'text-sky-300',
      warningColor: '#fde047',
      dangerColor: '#f87171',
      graphLineColor: '#38bdf8',
      graphFillColor: 'rgba(56, 189, 248, 0.15)',
      cornerStyle: 'rounded',
    },
  },

  blueprint: {
    definition: {
      id: 'blueprint',
      name: 'CAD Technical Blueprint',
      category: 'thematic',
      description:
        'Architectural engineering grid with pure drafting white on deep blueprint navy.',
      layout: 'bracket-hud',
      previewGradient: 'from-blue-600 via-blue-800 to-slate-950',
      accentColor: '#60a5fa',
      tags: ['Engineering', 'Blueprint', 'Technical', 'Grid'],
    },
    tokens: {
      fontFamily: 'font-mono text-xs',
      bgStyle: 'bg-blue-950/92 border border-blue-400/60 shadow-[0_0_20px_rgba(96,165,250,0.2)]',
      borderStyle: 'border-blue-400/60',
      accentColor: '#93c5fd',
      primaryTextColor: 'text-blue-200 font-semibold',
      secondaryTextColor: 'text-blue-400',
      warningColor: '#fde047',
      dangerColor: '#f87171',
      graphLineColor: '#93c5fd',
      graphFillColor: 'rgba(147, 197, 253, 0.15)',
      cornerStyle: 'sharp',
    },
  },

  steampunk: {
    definition: {
      id: 'steampunk',
      name: 'Steampunk Chronometer',
      category: 'thematic',
      description: 'Vintage brass, weathered copper, and warm parchment gauge typography.',
      layout: 'modular-cards',
      previewGradient: 'from-amber-600 via-yellow-700 to-stone-900',
      accentColor: '#d97706',
      tags: ['Brass', 'Copper', 'Vintage', 'Parchment'],
    },
    tokens: {
      fontFamily: 'font-serif font-bold',
      bgStyle:
        'bg-stone-950/95 border-2 border-amber-600/80 shadow-[0_0_25px_rgba(217,119,6,0.25)]',
      borderStyle: 'border-amber-600/80',
      accentColor: '#d97706',
      primaryTextColor: 'text-amber-300 font-bold',
      secondaryTextColor: 'text-yellow-600',
      warningColor: '#ea580c',
      dangerColor: '#991b1b',
      graphLineColor: '#d97706',
      graphFillColor: 'rgba(217, 119, 6, 0.2)',
      cornerStyle: 'rounded',
    },
  },
}

export const THEME_LIST = Object.values(THEME_REGISTRY).map((t) => t.definition)
